project:
  type: website
  output-dir: docs

website:
  title: "Site"
  reader-mode: true
  # repo-url: https://github.com/quarto-dev/quarto-demo
  # repo-actions: [edit, issue]
  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/klaxonklaxoff/site
          - text: Report a Bug
            url:  https://github.com/klaxonklaxoff/site/issues
      - icon: linkedin
        href: https://www.linkedin.com/in/brittnyvongdara/
    contents: 
    - href: index.qmd
      text: Landing page
    - href: about.qmd
      text: About me
      # text: Home
      # - section: Section 1
      #   - content:
page-footer:  
  - icon: github
    href: https://github.com/
  - icon: linkedin 
    href: https://www.linkedin.com/in/brittnyvongdara/ 

lang: en

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true