project:
  type: website

website:
  title: "My site"

  navbar:
    background: primary
    reader-mode: true
    search: true
  
    repo-url: https://github.com/klaxonklaxoff/site
    repo-actions: [edit, issue]

    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/klaxonklaxoff/klaxonklaxoff.github.io
          - text: Report a Bug
            url:  https://github.com/klaxonklaxoff/klaxonklaxoff.github.io/issues

    left:
      - text: Landing page
        file: index.qmd
      - text: Analysis
        menu:
          - file: nyt.qmd
          - text: PWHL stats
            file: pwhl_dv.qmd
          - file: bobs-burgers.qmd
      - text: Card games
        menu:
          - file: pi-deng.qmd
          - file: zole.qmd

    
page-footer:  
  - icon: github
    href: https://github.com/klaxonklaxoff
  - icon: linkedin 
    href: https://www.linkedin.com/in/brittnyvongdara/ 

lang: en

format:
  html:
    theme: 
      light: zephyr
      dark: darkly
    css: styles.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1200px
      margin-width: 300px
      gutter-width: 1.5rem
