project:
  type: website

website:
  title: "My site"

  navbar:
      background: primary
      search: true
      left:
        - text: Landing page
          file: index.qmd
        - text: About me
          file: about.qmd
        - text: Analysis
          menu:
            - text: New York Times crosswording
              file: nyt.qmd
            - text: PWHL
              file: pwhl_dv.qmd
        - text: Reference
          menu:
            - text: Zole
              file: zole.qmd

  reader-mode: true
  repo-url: https://github.com/klaxonklaxoff/site
  repo-actions: [edit, issue]
  
page-footer:  
  - icon: github
    href: https://github.com/klaxonklaxoff
  - icon: linkedin 
    href: https://www.linkedin.com/in/brittnyvongdara/ 

lang: en

format:
  html:
    theme: 
      light: minty
      dark: darkly
    css: styles.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1200px
      margin-width: 300px
      gutter-width: 1.5rem
