# https://github.com/pommevilla/friendly-dollop/blob/master/.github/workflows/quarto-render.yml
name: Render and deploy Quarto files
on: 
  push:
  pull_request:

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 2
        extra-packages: |
          any::dplyr
          any::ggplot2
          any::plotly
          any::scales
          any::MetBrewer
          
        needs: |
          website
          coverage

    - name: "Install Quarto and render"
      uses: pommevilla/quarto-render@main
      
#     - uses: r-lib/actions/setup-r@v3    
#     - name: print-message   
#         # Code to execute R script
#       run: Rscript -e "install.packages(c('dplyr', 'ggplot2', 'plotly', 'scales', 'MetBrewer'))

    - name: "Deploy to gh-pages"
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
