on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@main

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.2.0'

#       - name: Install R Dependencies
#         uses: r-lib/actions/setup-renv@v1
#         with:
#           cache-version: 1
      
      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          cache-version: 2
          extra-packages: |
            tidyverse
          needs: |
            website
            coverage

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
